### ISSUE TITLE
Missing script "start"

### ISSUE THREAD

**Issue by lkomar** [aliafsahnoudeh/node-express-typescript-heroku#1]
https://github.com/aliafsahnoudeh/node-express-typescript-heroku/blob/ff431046f5d57273d63d1f5beaf3a5e417f15715/package.json#L13

**Comment by aliafsahnoudeh** [comment]
Nice catch lkomar, thanks :)
Added the missing script

**Comment by ghost** [comment]
I didn't even see that you had this repo up since a week when I posted it, I wish it wasn't that cringe haha! Good luck :)
